---
title: "Homicide Graph"
author: "Lauren Smith"
date: "12/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(sf)
library(tigris)
library(forcats)
library(viridis)
```


### Read in data
```{r}
homicides <- read_csv("data/homicide-data.csv")
```

### View data
```{r}
head(homicides)
unique(homicides$city)
```

### Clean data to use Washington DC
```{r}
washington <- homicides %>%
  filter(city == "Washington")
washington$disposition[washington$disposition == "Closed without arrest"] <- "unsolved"
washington$disposition[washington$disposition == "Open/No arrest"] <- "unsolved"
washington$disposition[washington$disposition == "Closed by arrest"] <- "solved"
washington <- washington %>%
  select(uid, victim_race, disposition, lat, lon) %>%
  group_by(uid, victim_race, disposition, lat, lon) %>%
  count() %>%
  group_by(victim_race) %>%
  mutate(loc_homicides = sum(n))
head(washington)
```

### Set coordinates
```{r}
washington <- st_as_sf(washington, coords = c("lon", "lat")) %>%
  st_set_crs(4269)
head(washington)
```

### sf object
```{r}
washington_city <- blocks(state = "DC", class = "sf")
ggplot() + 
  geom_sf(data = washington_city, color = "gray") +
  geom_sf(data = washington, aes(color = victim_race %>% fct_lump_n(3)), size = 1) +
  scale_color_viridis(name = "race of victim", discrete = TRUE, direction = -1, option = "A") +
  facet_wrap(.~disposition)
```





















